# Travis CI configuration file for running tests
language: python

branches:
  only:
    - master

python:
  - "2.7"

services:
  - docker
  
addons:
  apt:
    packages:
      - nodejs
      - python-demjson

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install -o Dpkg::Options::="--force-confold" docker-engine

install:
  - "pip install --allow-all-external -r requirements.txt"
  - "pip install --allow-all-external demjson"

env:
  - MAKE_TARGET=test.syntax
  - MAKE_TARGET=test.edx_east_roles
  - MAKE_TARGET=docker.test.shard SHARD=0 SHARDS=3
  - MAKE_TARGET=docker.test.shard SHARD=1 SHARDS=3
  - MAKE_TARGET=docker.test.shard SHARD=2 SHARDS=3

script:
  - which comm
  - git diff --name-only ${TRAVIS_COMMIT_RANGE}
  - cd playbooks && grep -xF -f <(git diff --name-only ${TRAVIS_COMMIT_RANGE} | sort) <(python ../util/ansible-deps.py --playbook ../docker/plays/edxapp.yml --output-role-files | sort)
  - docker --version
  - make --version
  - travis_wait 50 make --keep-going $MAKE_TARGET SHARD=$SHARD SHARDS=$SHARDS
